<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>LocalRemote</AssemblyName>
    <RootNamespace>LocalRemote</RootNamespace>
    <Version>0.4.0</Version>
    <Authors>mderick.dev</Authors>
    <Company>mderick.dev</Company>
    <Copyright>By mderick.dev</Copyright>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
